# Generated by Django 3.2.9 on 2021-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('postale', models.CharField(max_length=255)),
                ('nb_parts', models.CharField(max_length=255)),
                ('mot_mairie', models.BooleanField(default=False)),
                ('carte_donnee', models.BooleanField(default=False)),
                ('presence_aux_distributions', models.BooleanField(default=False)),
                ('champ_remarque', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
