# Generated by Django 3.2.7 on 2021-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211126_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
