# Generated by Django 3.2.7 on 2021-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_beneficiaire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
